# Generated by Django 3.2.7 on 2022-07-15 03:14

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_type',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('base_doc', models.CharField(max_length=100)),
                ('base_doc_spring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('Colors_id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('Colors_name', models.CharField(max_length=10)),
                ('base_type_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Items_id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('Item_color_id', models.IntegerField()),
                ('Items_sex', models.IntegerField()),
                ('Items_name', models.CharField(max_length=20)),
                ('Items_explanaion', models.CharField(max_length=100)),
                ('Items_price', models.IntegerField()),
                ('Items_size', models.ImageField(upload_to='')),
                ('Items_maker', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(1, '女性'), (2, '男性'), (3, 'その他'), (4, '無回答')], default=1, max_length=100, verbose_name='gender')),
                ('img', models.ImageField(upload_to='media/', verbose_name='img')),
            ],
        ),
    ]
