# Generated by Django 3.2.7 on 2022-07-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='季節')),
                ('base', models.CharField(max_length=10, verbose_name='ベースタイプ')),
                ('base_doc', models.CharField(max_length=100, verbose_name='ベース説明')),
                ('color_doc', models.CharField(max_length=100, verbose_name='色の説明')),
            ],
            options={
                'verbose_name_plural': 'ベースタイプ',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='色名')),
                ('img', models.ImageField(upload_to='', verbose_name='色の画像')),
                ('base_type_id', models.IntegerField(verbose_name='ベースタイプ接続ID')),
            ],
            options={
                'verbose_name_plural': '色',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='アイテム名')),
                ('img', models.ImageField(upload_to='', verbose_name='アイテム画像')),
                ('gender', models.IntegerField(verbose_name='性別')),
                ('color_id', models.IntegerField(verbose_name='色テーブル接続ID')),
            ],
            options={
                'verbose_name_plural': 'アイテム',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(1, '女性'), (2, '男性'), (3, 'その他'), (4, '無回答')], default=1, max_length=100, verbose_name='gender')),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
            ],
        ),
    ]
