# Generated by Django 3.2.7 on 2022-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_color', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_type',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
