# Generated by Django 3.2.7 on 2022-07-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_type_id', models.IntegerField()),
                ('base_type_name', models.CharField(max_length=10)),
                ('base_type_base_doc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colors_name', models.CharField(max_length=10)),
                ('Colors_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items_id', models.IntegerField()),
                ('Items_sex', models.IntegerField()),
                ('Items_name', models.CharField(max_length=20)),
                ('Items_explanate', models.CharField(max_length=100)),
                ('Items_price', models.IntegerField()),
                ('Items_size', models.ImageField(upload_to='')),
                ('Items_maker', models.CharField(max_length=20)),
            ],
        ),
    ]
