# Generated by Django 3.2.7 on 2022-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_color', '0002_alter_sample_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('base', models.CharField(max_length=10)),
                ('img_path', models.CharField(max_length=10)),
                ('base_type_txt', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ベースタイプ',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('img_path', models.CharField(max_length=10)),
                ('base_type_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '色',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('Items_name', models.CharField(max_length=20)),
                ('img_path', models.CharField(max_length=10)),
                ('color_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'アイテム',
            },
        ),
        migrations.AlterField(
            model_name='sample',
            name='gender',
            field=models.CharField(choices=[(0, '女性'), (1, '男性'), (2, 'その他'), (3, '無回答')], default=0, max_length=100, verbose_name='gender'),
        ),
    ]
