# Generated by Django 3.2.7 on 2022-07-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_color', '0002_alter_base_type_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_type',
            name='user_id',
        ),
    ]
