# Generated by Django 3.2.7 on 2022-07-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_color', '0002_base_type_colors_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_type',
            name='base_type_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='Colors_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Items_explanate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Items_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
